import { and, desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { alerts, districts, emergencyContacts, incidents, preparednessResources, users, type InsertUser } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId, name: user.name, email: user.email, loginMethod: user.loginMethod, lastSignedIn: user.lastSignedIn || new Date(), role: user.role || (user.openId === ENV.ownerOpenId ? "admin" : "user") }; await db.insert(users).values(values).onDuplicateKeyUpdate({ set: { name: values.name, email: values.email, loginMethod: values.loginMethod, lastSignedIn: values.lastSignedIn, role: values.role } }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return rows[0]; }

const demoDistricts = [{ name: "Kailali", province: "Sudurpashchim", riskScore: 84, riskLevel: "elevated" }, { name: "Sindhupalchok", province: "Bagmati", riskScore: 78, riskLevel: "high" }, { name: "Sunsari", province: "Koshi", riskScore: 62, riskLevel: "watch" }, { name: "Gorkha", province: "Gandaki", riskScore: 55, riskLevel: "watch" }];
export async function getDashboardSnapshot() { const db = await getDb(); if (!db) return { districts: demoDistricts, nationalReadiness: 72, activeAlerts: 3, districtsOnWatch: 18, reportsResolved: 91 }; const rows = await db.select().from(districts).orderBy(desc(districts.riskScore)).limit(20); return { districts: rows, nationalReadiness: 72, activeAlerts: 3, districtsOnWatch: rows.filter(r => r.riskScore >= 55).length, reportsResolved: 91 }; }
export async function listAlerts() { const db = await getDb(); if (!db) return []; return db.select().from(alerts).where(eq(alerts.status, "published")).orderBy(desc(alerts.publishedAt)); }
export async function listPreparedness() { const db = await getDb(); if (!db) return []; return db.select().from(preparednessResources).orderBy(preparednessResources.disasterType); }
export async function listIncidents() { const db = await getDb(); if (!db) return []; return db.select().from(incidents).orderBy(desc(incidents.createdAt)).limit(100); }
export async function createIncident(input: { reporterId: number; disasterType: string; location: string; severity: "moderate" | "high" | "critical"; description: string; contactDetails?: string }) { const db = await getDb(); if (!db) return { id: 0, ...input, status: "submitted" as const }; const result = await db.insert(incidents).values(input); return { id: result[0].insertId, ...input, status: "submitted" as const }; }
export async function updateIncidentStatus(id: number, status: "submitted" | "reviewing" | "verified" | "resolved" | "rejected", reviewedBy: number) { const db = await getDb(); if (!db) return { id, status, reviewedBy }; await db.update(incidents).set({ status, reviewedBy }).where(eq(incidents.id, id)); return { id, status, reviewedBy }; }
export async function updateAlertStatus(id: number, status: "draft" | "published" | "resolved", publishedBy: number) { const db = await getDb(); if (!db) return { id, status, publishedBy }; await db.update(alerts).set({ status, publishedBy, publishedAt: status === "published" ? new Date() : undefined }).where(eq(alerts.id, id)); return { id, status, publishedBy }; }
